version: "3.9"
services:
  spring_app:
    build: .
    container_name: spring_app
    image: corto-java:1.0
    ports:
      - "8080:8080"
    depends_on:
      - spring_db
  spring_db:
    container_name: spring_db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
